sudo: false
language: python
python:
 - "2.7"
install:
 - git clone https://github.com/tabatkins/bikeshed.git
 - pip install pygments
 - pip install --editable $PWD/bikeshed
 - bikeshed update
script:
 - bikeshed papers/dxxxxr0.bs docs/dxxxxr0.html
